### ISSUE TITLE
Qt version

### ISSUE THREAD

**Issue by tatbag** [rectalogic/webvfx#7]
Hi,

I want to check what version of QT should I use, because I get this error when running qmake:

Project ERROR: Unknown module(s) in QT: declarative webkit

this is the output of qmake -v:
QMake version 3.0
Using Qt version 5.0.2 in /usr/lib/x86_64-linux-gnu

Thanks!

**Comment by rectalogic** [comment]
It should work with Qt 4.7.3.  ddennedy has a fork that should work with Qt 5.x - I haven't merged it yet and I need to check the state of WebGL in webkit1 under Qt 5
https://github.com/ddennedy/webvfx
